import 'dotenv/config';
import express from 'express';
import cors from 'cors';
import helmet from 'helmet';
import { rateLimit } from 'express-rate-limit';
import auth from './routes/auth.js';
import api from './routes/api.js';

if (!process.env.JWT_SECRET) throw new Error('Falta JWT_SECRET');
const app = express();
const origins = [process.env.FRONTEND_URL, 'http://localhost:5173'].filter(Boolean);
app.set('trust proxy', 1);
app.use(helmet());
app.use(cors({ origin(origin, cb) { if (!origin || origins.includes(origin)) return cb(null, true); cb(new Error('Origen no autorizado')); } }));
app.use(express.json({ limit: '1mb' }));
app.use('/api/auth/login', rateLimit({ windowMs: 15 * 60 * 1000, limit: 10, standardHeaders: true, legacyHeaders: false }));
app.get('/', (_req, res) => res.json({ sistema: 'HotelControl', estado: 'activo', version: '2.0.0' }));
app.get('/api/health', (_req, res) => res.json({ ok: true, mode: process.env.DATA_MODE || 'apps-script' }));
app.use('/api/auth', auth);
app.use('/api', api);
app.use((_req, res) => res.status(404).json({ mensaje: 'Ruta no encontrada' }));
app.use((err, _req, res, _next) => { console.error(err); res.status(500).json({ mensaje: err.message || 'Error interno' }); });
const port = process.env.PORT || 4000;
app.listen(port, '0.0.0.0', () => console.log(`HotelControl API activa en puerto ${port}`));
