import { useEffect, useMemo, useState } from 'react';
import { BedDouble, BookOpen, Building2, Eye, EyeOff, LayoutDashboard, LogOut, Menu, Plus, ShieldCheck, UserCog, Users, WalletCards, X } from 'lucide-react';

const API_URL = import.meta.env.VITE_API_URL || 'http://localhost:4000/api';
const money = n => new Intl.NumberFormat('es-BO',{style:'currency',currency:'BOB'}).format(Number(n||0));
const stored = () => { try { return JSON.parse(localStorage.getItem('hotel_session') || 'null'); } catch { return null; } };

async function api(path, options = {}, token = '') {
  const response = await fetch(`${API_URL}${path}`, {
    ...options,
    headers: { 'Content-Type':'application/json', ...(token ? { Authorization:`Bearer ${token}` } : {}), ...(options.headers || {}) }
  });
  const data = await response.json().catch(() => ({}));
  if (!response.ok) throw new Error(data.mensaje || 'No se pudo completar la solicitud');
  return data;
}

export default function App(){
  const [session,setSession] = useState(stored);
  const [configured,setConfigured] = useState(true);
  const [loadingStatus,setLoadingStatus] = useState(true);
  useEffect(()=>{ api('/auth/status').then(r=>setConfigured(r.configurado)).catch(()=>setConfigured(true)).finally(()=>setLoadingStatus(false)); },[]);
  const onLogin = value => { localStorage.setItem('hotel_session',JSON.stringify(value)); setSession(value); };
  const logout = () => { localStorage.removeItem('hotel_session'); setSession(null); };
  if(loadingStatus) return <Splash/>;
  if(!configured) return <Setup onReady={()=>setConfigured(true)}/>;
  if(!session) return <Login onLogin={onLogin}/>;
  return <HotelApp session={session} logout={logout}/>;
}

function Splash(){return <div className="auth-shell"><div className="splash-card"><div className="logo-mark"><Building2/></div><h1>HotelControl</h1><p>Preparando el sistema...</p><div className="spinner"/></div></div>}

function Login({onLogin}){
  const [show,setShow]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
  const submit=async e=>{e.preventDefault();setBusy(true);setError('');const f=Object.fromEntries(new FormData(e.currentTarget));try{onLogin(await api('/auth/login',{method:'POST',body:JSON.stringify(f)}));}catch(err){setError(err.message)}finally{setBusy(false)}};
  return <div className="auth-shell"><section className="auth-hero"><div className="hero-content"><div className="brand-large"><span><Building2/></span>HotelControl</div><h1>Administración hotelera clara, segura y en tiempo real.</h1><p>Controle habitaciones, huéspedes, reservas y pagos desde cualquier dispositivo.</p><div className="hero-points"><span><ShieldCheck/> Acceso protegido por roles</span><span><LayoutDashboard/> Información centralizada</span></div></div></section><section className="auth-panel"><form className="auth-card" onSubmit={submit}><div className="eyebrow">ACCESO AL SISTEMA</div><h2>Bienvenido</h2><p>Ingrese sus credenciales institucionales.</p>{error&&<div className="alert error">{error}</div>}<label>Correo electrónico<input name="correo" type="email" placeholder="admin@hotel.com" required autoFocus/></label><label>Contraseña<div className="password"><input name="password" type={show?'text':'password'} placeholder="••••••••" required/><button type="button" onClick={()=>setShow(!show)}>{show?<EyeOff/>:<Eye/>}</button></div></label><button className="primary full" disabled={busy}>{busy?'Verificando...':'Ingresar'}</button><small className="auth-note">La sesión se cierra automáticamente al vencer el token de acceso.</small></form></section></div>
}

function Setup({onReady}){
  const [busy,setBusy]=useState(false),[message,setMessage]=useState('');
  const submit=async e=>{e.preventDefault();setBusy(true);setMessage('');const f=Object.fromEntries(new FormData(e.currentTarget));try{await api('/auth/setup',{method:'POST',body:JSON.stringify(f)});setMessage('Administrador creado. Ya puede iniciar sesión.');setTimeout(onReady,900);}catch(err){setMessage(err.message)}finally{setBusy(false)}};
  return <div className="auth-shell setup"><section className="auth-panel"><form className="auth-card" onSubmit={submit}><div className="logo-mark"><ShieldCheck/></div><div className="eyebrow">CONFIGURACIÓN INICIAL</div><h2>Crear administrador</h2><p>Esta pantalla solo aparece cuando la hoja Usuarios está vacía.</p>{message&&<div className="alert">{message}</div>}<label>Nombre completo<input name="nombre" required/></label><label>Correo<input name="correo" type="email" required/></label><label>Contraseña inicial<input name="password" type="password" minLength="8" required/></label><label>Clave de instalación<input name="setupKey" type="password" required/></label><button className="primary full" disabled={busy}>{busy?'Creando...':'Crear administrador'}</button></form></section></div>
}

function HotelApp({session,logout}){
  const {token,usuario}=session;
  const [page,setPage]=useState('dashboard'),[open,setOpen]=useState(false),[dash,setDash]=useState({}),[rooms,setRooms]=useState([]),[guests,setGuests]=useState([]),[bookings,setBookings]=useState([]),[users,setUsers]=useState([]),[modal,setModal]=useState(null),[msg,setMsg]=useState(''),[busy,setBusy]=useState(true);
  const isAdmin=usuario.rol==='Administrador';
  const nav=useMemo(()=>[['dashboard','Panel',LayoutDashboard],['reservas','Reservas',BookOpen],['habitaciones','Habitaciones',BedDouble],['huespedes','Huéspedes',Users],['pagos','Pagos',WalletCards],...(isAdmin?[['usuarios','Usuarios',UserCog]]:[])],[isAdmin]);
  const load=async()=>{setBusy(true);try{const requests=[api('/dashboard',{},token),api('/habitaciones',{},token),api('/huespedes',{},token),api('/reservas',{},token)];const [d,h,g,r]=await Promise.all(requests);setDash(d);setRooms(h);setGuests(g);setBookings(r);if(isAdmin)setUsers(await api('/auth/usuarios',{},token));}catch(e){setMsg(e.message);if(/Sesión/.test(e.message))logout()}finally{setBusy(false)}};
  useEffect(()=>{load()},[]);
  const save=async e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget));try{const endpoint=modal==='usuarios'?'/auth/usuarios':`/${modal}`;await api(endpoint,{method:'POST',body:JSON.stringify(f)},token);setModal(null);setMsg('Registro guardado correctamente');load()}catch(err){setMsg(err.message)}};
  return <div className="app"><aside className={open?'side open':'side'}><div className="brand"><span><Building2/></span><div><b>HotelControl</b><small>Administración</small></div><button className="icon mobile" onClick={()=>setOpen(false)}><X/></button></div><nav>{nav.map(([id,label,Icon])=><button key={id} className={page===id?'active':''} onClick={()=>{setPage(id);setOpen(false)}}><Icon/>{label}</button>)}</nav><div className="user"><div className="avatar">{usuario.nombre?.split(' ').map(x=>x[0]).slice(0,2).join('')}</div><span><b>{usuario.nombre}</b><small>{usuario.rol}</small></span><button className="icon" title="Cerrar sesión" onClick={logout}><LogOut/></button></div></aside><main><header><button className="icon mobile" onClick={()=>setOpen(true)}><Menu/></button><div><h1>{nav.find(x=>x[0]===page)?.[1]}</h1><p>Gestión centralizada del hotel</p></div><span className="status"><i/> Sistema activo</span></header>{msg&&<div className="notice" onClick={()=>setMsg('')}>{msg}</div>}<section className="content">{busy?<Loading/>:<>{page==='dashboard'&&<Dashboard d={dash} rooms={rooms} bookings={bookings}/>} {page==='habitaciones'&&<TablePage title="Habitaciones" button="Nueva habitación" onAdd={()=>setModal('habitaciones')} canAdd={['Administrador','Recepcionista'].includes(usuario.rol)} headers={['Número','Tipo','Capacidad','Precio','Estado','Piso']} rows={rooms.map(x=>[x.numero,x.tipo,x.capacidad,money(x.precio),<Badge key={x.id} text={x.estado}/>,x.piso])}/>} {page==='huespedes'&&<TablePage title="Huéspedes" button="Nuevo huésped" onAdd={()=>setModal('huespedes')} canAdd={['Administrador','Recepcionista'].includes(usuario.rol)} headers={['Nombre','Documento','Teléfono','Correo','Nacionalidad']} rows={guests.map(x=>[x.nombre,x.documento,x.telefono,x.correo,x.nacionalidad])}/>} {page==='reservas'&&<TablePage title="Reservas" button="Nueva reserva" onAdd={()=>setModal('reservas')} canAdd={['Administrador','Recepcionista'].includes(usuario.rol)} headers={['Código','Huésped','Habitación','Entrada','Salida','Estado','Total']} rows={bookings.map(x=>[x.id,guests.find(g=>g.id===x.huespedId)?.nombre||x.huespedId,rooms.find(r=>r.id===x.habitacionId)?.numero||x.habitacionId,x.entrada,x.salida,<Badge key={x.id} text={x.estado}/>,money(x.total)])}/>} {page==='pagos'&&<div className="empty"><WalletCards/><h2>Módulo de pagos</h2><p>Cobrado {money(dash.ingresos)} · Pendiente {money(dash.pendiente)}</p></div>} {page==='usuarios'&&<TablePage title="Usuarios del sistema" button="Nuevo usuario" onAdd={()=>setModal('usuarios')} canAdd={isAdmin} headers={['Nombre','Correo','Rol','Estado']} rows={users.map(x=>[x.nombre,x.correo,<Badge key={x.id} text={x.rol}/>,x.estado])}/>}</>}</section></main>{modal&&<Modal type={modal} close={()=>setModal(null)} save={save} rooms={rooms} guests={guests}/>}</div>
}

function Loading(){return <div className="loading"><div className="spinner"/><p>Cargando información...</p></div>}
function Dashboard({d,rooms,bookings}){const cards=[['Habitaciones',d.habitaciones,'Total registrado'],['Disponibles',d.disponibles,'Listas para asignar'],['Ocupadas',d.ocupadas,'Con huéspedes'],['Reservas activas',d.reservasActivas,'Confirmadas o en curso']];return <><div className="cards">{cards.map(([a,b,c])=><article key={a}><small>{a}</small><strong>{b??0}</strong><span>{c}</span></article>)}<article><small>Ingresos registrados</small><strong>{money(d.ingresos)}</strong><span>Adelantos y pagos</span></article><article><small>Saldo pendiente</small><strong>{money(d.pendiente)}</strong><span>Por cobrar</span></article></div><div className="grid"><article className="panel"><div className="panelhead"><div><h2>Estado de habitaciones</h2><p>Vista operativa actual</p></div></div>{rooms.slice(0,8).map(r=><div className="room" key={r.id}><b>{r.numero}</b><span>{r.tipo}</span><Badge text={r.estado}/></div>)}</article><article className="panel"><div className="panelhead"><div><h2>Reservas recientes</h2><p>Últimos movimientos</p></div></div>{bookings.length?bookings.slice(-8).reverse().map(r=><div className="room" key={r.id}><b>{r.id}</b><span>{r.entrada} → {r.salida}</span><Badge text={r.estado}/></div>):<p className="muted">Sin reservas registradas.</p>}</article></div></>}
function TablePage({title,button,onAdd,headers,rows,canAdd}){return <article className="panel"><div className="panelhead"><div><h2>{title}</h2><p>{rows.length} registros</p></div>{canAdd&&<button className="primary" onClick={onAdd}><Plus/> {button}</button>}</div><div className="tablewrap"><table><thead><tr>{headers.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.length?rows.map((r,i)=><tr key={i}>{r.map((v,j)=><td key={j}>{v}</td>)}</tr>):<tr><td colSpan={headers.length} className="empty-row">No existen registros.</td></tr>}</tbody></table></div></article>}
function Badge({text}){return <span className={`badge ${String(text).toLowerCase().replaceAll(' ','-')}`}>{text}</span>}
function Modal({type,close,save,rooms,guests}){return <div className="overlay"><form className="modal" onSubmit={save}><div className="panelhead"><div><div className="eyebrow">NUEVO REGISTRO</div><h2>{type==='usuarios'?'Crear usuario':type[0].toUpperCase()+type.slice(1)}</h2></div><button type="button" className="icon" onClick={close}><X/></button></div><div className="form-grid">{type==='habitaciones'&&<><Input n="numero" l="Número"/><Input n="tipo" l="Tipo"/><Input n="capacidad" l="Capacidad" type="number"/><Input n="precio" l="Precio por noche" type="number"/><Select n="estado" l="Estado" opts={['Disponible','Ocupada','Limpieza','Mantenimiento']}/><Input n="piso" l="Piso" type="number"/><Input n="observaciones" l="Observaciones" wide/></>}{type==='huespedes'&&<><Input n="nombre" l="Nombre completo" wide/><Input n="documento" l="Documento"/><Input n="telefono" l="Teléfono"/><Input n="correo" l="Correo" type="email"/><Input n="nacionalidad" l="Nacionalidad"/></>}{type==='reservas'&&<><Select n="huespedId" l="Huésped" opts={guests.map(x=>[x.id,x.nombre])} wide/><Select n="habitacionId" l="Habitación" opts={rooms.filter(x=>x.estado!=='Mantenimiento').map(x=>[x.id,`${x.numero} - ${x.tipo}`])} wide/><Input n="entrada" l="Entrada" type="date"/><Input n="salida" l="Salida" type="date"/><Input n="personas" l="Personas" type="number"/><Select n="estado" l="Estado" opts={['Pendiente','Confirmada','En curso']}/><Input n="total" l="Total" type="number"/><Input n="pagado" l="Pagado" type="number"/></>}{type==='usuarios'&&<><Input n="nombre" l="Nombre completo" wide/><Input n="correo" l="Correo" type="email" wide/><Input n="password" l="Contraseña inicial" type="password"/><Select n="rol" l="Rol" opts={['Administrador','Recepcionista','Gerencia','Limpieza','Mantenimiento']}/><Select n="estado" l="Estado" opts={['Activo','Inactivo']}/></>}</div><div className="modal-actions"><button type="button" className="secondary" onClick={close}>Cancelar</button><button className="primary">Guardar registro</button></div></form></div>}
function Input({n,l,type='text',wide=false}){return <label className={wide?'wide':''}>{l}<input required name={n} type={type}/></label>}
function Select({n,l,opts,wide=false}){return <label className={wide?'wide':''}>{l}<select required name={n}><option value="">Seleccione...</option>{opts.map((o,i)=>Array.isArray(o)?<option key={i} value={o[0]}>{o[1]}</option>:<option key={i}>{o}</option>)}</select></label>}
