import {useEffect,useState} from 'react';
import {BedDouble,BookOpen,LayoutDashboard,Menu,Plus,Users,WalletCards,X} from 'lucide-react';
const api=async(path,options={})=>{const r=await fetch(`/api${path}`,{headers:{'Content-Type':'application/json'},...options});const data=await r.json();if(!r.ok)throw new Error(data.mensaje||'Error');return data};
const money=n=>new Intl.NumberFormat('es-BO',{style:'currency',currency:'BOB'}).format(n||0);

export default function App(){
 const[page,setPage]=useState('dashboard'),[open,setOpen]=useState(false),[dash,setDash]=useState({}),[rooms,setRooms]=useState([]),[guests,setGuests]=useState([]),[bookings,setBookings]=useState([]),[modal,setModal]=useState(null),[msg,setMsg]=useState('');
 const load=async()=>{try{const[d,h,g,r]=await Promise.all([api('/dashboard'),api('/habitaciones'),api('/huespedes'),api('/reservas')]);setDash(d);setRooms(h);setGuests(g);setBookings(r)}catch(e){setMsg(e.message)}};
 useEffect(()=>{load()},[]);
 const nav=[['dashboard','Panel',LayoutDashboard],['reservas','Reservas',BookOpen],['habitaciones','Habitaciones',BedDouble],['huespedes','Huéspedes',Users],['pagos','Pagos',WalletCards]];
 const save=async(e)=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget));try{await api(`/${modal}`,{method:'POST',body:JSON.stringify(f)});setModal(null);setMsg('Registro guardado correctamente');load()}catch(err){setMsg(err.message)}};
 return <div className="app">
  <aside className={open?'side open':'side'}><div className="brand"><span>H</span><div><b>HotelControl</b><small>Administración</small></div><button className="icon mobile" onClick={()=>setOpen(false)}><X/></button></div><nav>{nav.map(([id,label,Icon])=><button key={id} className={page===id?'active':''} onClick={()=>{setPage(id);setOpen(false)}}><Icon/>{label}</button>)}</nav><div className="user"><div>AD</div><span><b>Administrador</b><small>Sesión local</small></span></div></aside>
  <main><header><button className="icon mobile" onClick={()=>setOpen(true)}><Menu/></button><div><h1>{nav.find(x=>x[0]===page)?.[1]}</h1><p>Gestión centralizada del hotel</p></div><span className="status">● Sistema activo</span></header>
  {msg&&<div className="notice" onClick={()=>setMsg('')}>{msg}</div>}
  <section className="content">
   {page==='dashboard'&&<Dashboard d={dash} rooms={rooms} bookings={bookings}/>} 
   {page==='habitaciones'&&<TablePage title="Habitaciones" button="Nueva habitación" onAdd={()=>setModal('habitaciones')} headers={['Número','Tipo','Capacidad','Precio','Estado','Piso']} rows={rooms.map(x=>[x.numero,x.tipo,x.capacidad,money(x.precio),<Badge key={x.id} text={x.estado}/>,x.piso])}/>} 
   {page==='huespedes'&&<TablePage title="Huéspedes" button="Nuevo huésped" onAdd={()=>setModal('huespedes')} headers={['Nombre','Documento','Teléfono','Correo','Nacionalidad']} rows={guests.map(x=>[x.nombre,x.documento,x.telefono,x.correo,x.nacionalidad])}/>} 
   {page==='reservas'&&<TablePage title="Reservas" button="Nueva reserva" onAdd={()=>setModal('reservas')} headers={['Código','Huésped','Habitación','Entrada','Salida','Estado','Total']} rows={bookings.map(x=>[x.id,guests.find(g=>g.id===x.huespedId)?.nombre||x.huespedId,rooms.find(r=>r.id===x.habitacionId)?.numero||x.habitacionId,x.entrada,x.salida,<Badge key={x.id} text={x.estado}/>,money(x.total)])}/>} 
   {page==='pagos'&&<div className="empty"><WalletCards/><h2>Módulo de pagos</h2><p>Resumen actual: cobrado {money(dash.ingresos)} y pendiente {money(dash.pendiente)}.</p></div>}
  </section></main>
  {modal&&<Modal type={modal} close={()=>setModal(null)} save={save} rooms={rooms} guests={guests}/>} 
 </div>
}
function Dashboard({d,rooms,bookings}){const cards=[['Habitaciones',d.habitaciones],['Disponibles',d.disponibles],['Ocupadas',d.ocupadas],['Reservas activas',d.reservasActivas]];return <><div className="cards">{cards.map(x=><article><small>{x[0]}</small><strong>{x[1]??0}</strong></article>)}<article><small>Ingresos registrados</small><strong>{money(d.ingresos)}</strong></article><article><small>Saldo pendiente</small><strong>{money(d.pendiente)}</strong></article></div><div className="grid"><article className="panel"><h2>Estado de habitaciones</h2>{rooms.map(r=><div className="room"><b>{r.numero}</b><span>{r.tipo}</span><Badge text={r.estado}/></div>)}</article><article className="panel"><h2>Reservas recientes</h2>{bookings.length?bookings.map(r=><div className="room"><b>{r.id}</b><span>{r.entrada} → {r.salida}</span><Badge text={r.estado}/></div>):<p>Sin reservas registradas.</p>}</article></div></>}
function TablePage({title,button,onAdd,headers,rows}){return <article className="panel"><div className="panelhead"><h2>{title}</h2><button className="primary" onClick={onAdd}><Plus/> {button}</button></div><div className="tablewrap"><table><thead><tr>{headers.map(h=><th>{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{r.map((v,j)=><td key={j}>{v}</td>)}</tr>)}</tbody></table></div></article>}
function Badge({text}){return <span className={`badge ${String(text).toLowerCase().replaceAll(' ','-')}`}>{text}</span>}
function Modal({type,close,save,rooms,guests}){return <div className="overlay"><form className="modal" onSubmit={save}><div className="panelhead"><h2>Nuevo registro</h2><button type="button" className="icon" onClick={close}><X/></button></div>{type==='habitaciones'&&<><Input n="numero" l="Número"/><Input n="tipo" l="Tipo"/><Input n="capacidad" l="Capacidad" type="number"/><Input n="precio" l="Precio por noche" type="number"/><Select n="estado" l="Estado" opts={['Disponible','Ocupada','Limpieza','Mantenimiento']}/><Input n="piso" l="Piso" type="number"/><Input n="observaciones" l="Observaciones"/></>}{type==='huespedes'&&<><Input n="nombre" l="Nombre completo"/><Input n="documento" l="Documento"/><Input n="telefono" l="Teléfono"/><Input n="correo" l="Correo" type="email"/><Input n="nacionalidad" l="Nacionalidad"/></>}{type==='reservas'&&<><Select n="huespedId" l="Huésped" opts={guests.map(x=>[x.id,x.nombre])}/><Select n="habitacionId" l="Habitación" opts={rooms.filter(x=>x.estado!=='Mantenimiento').map(x=>[x.id,`${x.numero} - ${x.tipo}`])}/><Input n="entrada" l="Entrada" type="date"/><Input n="salida" l="Salida" type="date"/><Input n="personas" l="Personas" type="number"/><Select n="estado" l="Estado" opts={['Pendiente','Confirmada','En curso']}/><Input n="total" l="Total" type="number"/><Input n="pagado" l="Pagado" type="number"/></>}<button className="primary full">Guardar</button></form></div>}
function Input({n,l,type='text'}){return <label>{l}<input required name={n} type={type}/></label>};function Select({n,l,opts}){return <label>{l}<select required name={n}><option value="">Seleccione...</option>{opts.map(o=>Array.isArray(o)?<option value={o[0]}>{o[1]}</option>:<option>{o}</option>)}</select></label>}
