import {useEffect,useMemo,useState} from 'react';
import {BedDouble,BookOpen,Building2,CalendarDays,ChevronLeft,ChevronRight,Download,Edit3,Eye,EyeOff,FileText,LogOut,Menu,Phone,Plus,Power,Printer,Search,Settings,ShieldCheck,UserCog,Users,WalletCards,ClipboardCheck,CheckCircle2,PlayCircle,Wrench,AlertTriangle,X} from 'lucide-react';

const API_URL=import.meta.env.VITE_API_URL||'http://localhost:4000/api';
const money=n=>new Intl.NumberFormat('es-BO',{style:'currency',currency:'BOB'}).format(Number(n||0));
const stored=()=>{try{return JSON.parse(localStorage.getItem('hotel_session')||'null')}catch{return null}};
const iso=d=>{const x=new Date(d);return `${x.getFullYear()}-${String(x.getMonth()+1).padStart(2,'0')}-${String(x.getDate()).padStart(2,'0')}`};
const parseDate=v=>{if(!v)return null;if(v.includes('/')){const [d,m,y]=v.split('/');return new Date(+y,+m-1,+d)}return new Date(`${v}T00:00:00`)};
const initials=n=>String(n||'').split(/\s+/).map(x=>x[0]).join('').slice(0,2).toUpperCase();
const normalizeBookingState=v=>{const x=String(v||'').trim().toLowerCase();if(['confirmada','reservada','pendiente'].includes(x))return 'Reservada';if(['ocupada','en curso','en_curso'].includes(x))return 'Ocupada';if(x==='finalizada')return 'Finalizada';if(x==='cancelada')return 'Cancelada';return v||'Reservada'};
async function api(path,options={},token=''){const r=await fetch(`${API_URL}${path}`,{...options,headers:{'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{}) ,...(options.headers||{})}});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.mensaje||'No se pudo completar la solicitud');return d}

export default function App(){const[session,setSession]=useState(stored),[configured,setConfigured]=useState(true),[loading,setLoading]=useState(true);useEffect(()=>{api('/auth/status').then(x=>setConfigured(x.configurado)).catch(()=>setConfigured(true)).finally(()=>setLoading(false))},[]);const login=v=>{localStorage.setItem('hotel_session',JSON.stringify(v));setSession(v)};const logout=()=>{localStorage.removeItem('hotel_session');setSession(null)};if(loading)return <Splash/>;if(!configured)return <Setup ready={()=>setConfigured(true)}/>;if(!session)return <Login done={login}/>;return <HotelApp session={session} logout={logout}/>}
function Splash(){return <div className="auth-shell"><div className="auth-card center"><Building2 size={48}/><h1>HotelControl</h1><p>Preparando el sistema…</p></div></div>}
function Login({done}){const[show,setShow]=useState(false),[msg,setMsg]=useState(''),[busy,setBusy]=useState(false);const submit=async e=>{e.preventDefault();setBusy(true);setMsg('');try{done(await api('/auth/login',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(e.currentTarget)))}))}catch(x){setMsg(x.message)}finally{setBusy(false)}};return <div className="auth-shell"><section className="auth-hero"><div><div className="brand-large"><Building2/> HotelControl</div><h1>Gestión sencilla para hospedajes, reservas y cobros.</h1><p>Diseñado para trabajar cómodamente desde celular o computadora.</p></div></section><section className="auth-panel"><form className="auth-card" onSubmit={submit}><small>ACCESO SEGURO</small><h2>Iniciar sesión</h2>{msg&&<div className="alert error">{msg}</div>}<label>Correo<input name="correo" type="email" required/></label><label>Contraseña<div className="password"><input name="password" type={show?'text':'password'} required/><button type="button" onClick={()=>setShow(!show)}>{show?<EyeOff/>:<Eye/>}</button></div></label><button className="primary full" disabled={busy}>{busy?'Verificando…':'Ingresar'}</button></form></section></div>}
function Setup({ready}){const[msg,setMsg]=useState('');const submit=async e=>{e.preventDefault();try{await api('/auth/setup',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(e.currentTarget)))});setMsg('Administrador creado');setTimeout(ready,700)}catch(x){setMsg(x.message)}};return <div className="auth-shell"><form className="auth-card" onSubmit={submit}><ShieldCheck size={42}/><h2>Configuración inicial</h2>{msg&&<div className="alert">{msg}</div>}<label>Nombre<input name="nombre" required/></label><label>Correo<input name="correo" type="email" required/></label><label>Contraseña<input name="password" type="password" minLength="8" required/></label><label>Clave de instalación<input name="setupKey" type="password" required/></label><button className="primary full">Crear administrador</button></form></div>}

function HotelApp({session,logout}){
 const{token,usuario}=session;const[page,setPage]=useState('calendario'),[open,setOpen]=useState(false),[dash,setDash]=useState({}),[hospedajes,setHospedajes]=useState([]),[rooms,setRooms]=useState([]),[guests,setGuests]=useState([]),[bookings,setBookings]=useState([]),[registro,setRegistro]=useState([]),[payments,setPayments]=useState([]),[cleaning,setCleaning]=useState([]),[maintenance,setMaintenance]=useState([]),[users,setUsers]=useState([]),[modal,setModal]=useState(null),[reservationDraft,setReservationDraft]=useState(null),[selected,setSelected]=useState(null),[msg,setMsg]=useState(''),[busy,setBusy]=useState(true),[month,setMonth]=useState(new Date()),[hotelFilter,setHotelFilter]=useState('todos');
 const isAdmin=usuario.rol==='Administrador';
 const nav=useMemo(()=>[['calendario','Calendario',CalendarDays],['reservas','Reservas',BookOpen],['registro','Registro',FileText],['pagos','Pagos',WalletCards],['limpieza','Limpieza',ClipboardCheck],['mantenimiento','Mantenimiento',Wrench],...(isAdmin?[['config','Configuración',Settings],['usuarios','Usuarios',UserCog]]:[])],[isAdmin]);
 const load=async()=>{setBusy(true);try{const[d,hs,r,g,b,reg,pays,clean,maint]=await Promise.all([api('/dashboard',{},token),api('/hospedajes',{},token),api('/habitaciones',{},token),api('/huespedes',{},token),api('/reservas',{},token),api('/registro',{},token),api('/pagos',{},token),api('/limpieza',{},token),api('/mantenimiento',{},token)]);setDash(d);setHospedajes(hs);setRooms(r);setGuests(g);setBookings(b);setRegistro(reg);setPayments(pays);setCleaning(clean);setMaintenance(maint);if(isAdmin)setUsers(await api('/auth/usuarios',{},token))}catch(e){setMsg(e.message);if(/Sesión/.test(e.message))logout()}finally{setBusy(false)}};
 useEffect(()=>{load()},[]);
 const guest=id=>guests.find(x=>x.id===id)||{};const room=id=>rooms.find(x=>x.id===id)||{};const hotel=id=>hospedajes.find(x=>x.id===id)||{};
 const save=async(e)=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget));try{let endpoint=modal==='usuarios'?'/auth/usuarios':`/${modal}`;await api(endpoint,{method:'POST',body:JSON.stringify(f)},token);setModal(null);setMsg('Registro guardado correctamente');load()}catch(x){setMsg(x.message)}};
 const cleaningAction=async(id,accion)=>{try{await api(`/limpieza/${id}/accion`,{method:'POST',body:JSON.stringify({accion})},token);setMsg(accion==='finalizar'?'Habitación liberada correctamente':'Limpieza iniciada');load()}catch(x){setMsg(x.message)}};
 const maintenanceAction=async(id,accion)=>{try{await api(`/mantenimiento/${id}/accion`,{method:'POST',body:JSON.stringify({accion})},token);setMsg(accion==='finalizar'?'Mantenimiento finalizado; habitación enviada a limpieza':accion==='iniciar'?'Mantenimiento iniciado':'Registro actualizado');load()}catch(x){setMsg(x.message)}};
 const sendMaintenance=async r=>{const problema=prompt(`Problema de la habitación ${r.numero}`);if(!problema)return;const prioridad=prompt('Prioridad: Baja, Media, Alta o Urgente','Media')||'Media';try{await api('/mantenimiento',{method:'POST',body:JSON.stringify({habitacionId:r.id,problema,prioridad})},token);setMsg('Habitación enviada a mantenimiento');load()}catch(x){setMsg(x.message)}};
 const sendCleaning=async r=>{if(!confirm(`¿Enviar la habitación ${r.numero} a limpieza?`))return;try{await api(`/habitaciones/${r.id}/estado`,{method:'POST',body:JSON.stringify({estado:'Limpieza'})},token);setMsg('Habitación enviada a limpieza');load()}catch(x){setMsg(x.message)}};
 const deletePayment=async(id)=>{const motivo=prompt('Motivo de la anulación','Pago cargado por error');if(motivo===null)return;try{await api(`/pagos/${id}/anular`,{method:'POST',body:JSON.stringify({motivo})},token);setMsg('Pago anulado correctamente');setSelected(null);await load()}catch(x){setMsg(x.message)}};
 const action=async(id,data)=>{try{const response=await api(`/reservas/${id}/accion`,{method:'POST',body:JSON.stringify(data)},token);setSelected(null);setModal(null);setMsg(response.mensaje||'Operación realizada correctamente');await load()}catch(x){setMsg(x.message)}};
 const editHotel=async h=>{const nombre=prompt('Nombre del hospedaje',h.nombre);if(nombre===null)return;const direccion=prompt('Dirección',h.direccion||'');if(direccion===null)return;try{await api(`/hospedajes/${h.id}`,{method:'PATCH',body:JSON.stringify({nombre,direccion,estado:h.estado})},token);setMsg('Hospedaje actualizado');load()}catch(x){setMsg(x.message)}};
 const toggleHotel=async h=>{const estado=h.estado==='Inactivo'?'Activo':'Inactivo';if(!confirm(`${estado==='Inactivo'?'Desactivar':'Activar'} ${h.nombre}? Los registros históricos se conservarán.`))return;try{await api(`/hospedajes/${h.id}`,{method:'PATCH',body:JSON.stringify({nombre:h.nombre,direccion:h.direccion,estado})},token);setMsg(`Hospedaje ${estado.toLowerCase()}`);load()}catch(x){setMsg(x.message)}};
 const editRoom=async r=>{const numero=prompt('Nombre de la habitación (ej. Hab. 1 (5 camas))',r.numero);if(numero===null)return;const capacidad=prompt('Cantidad de camas / capacidad',r.capacidad);if(capacidad===null)return;const precio=prompt('Precio por noche',r.precio);if(precio===null)return;const estado=prompt('Estado: Disponible, En alquiler, Limpieza, Mantenimiento o Fuera de servicio',r.estado)||r.estado;try{await api(`/habitaciones/${r.id}`,{method:'PATCH',body:JSON.stringify({numero,tipo:r.tipo,capacidad,precio,estado,piso:r.piso,activo:r.activo,observaciones:r.observaciones,hospedajeId:r.hospedajeId})},token);setMsg('Habitación actualizada');load()}catch(x){setMsg(x.message)}};
 const toggleRoom=async r=>{const activo=r.activo==='No'?'Sí':'No';if(!confirm(`${activo==='No'?'Desactivar':'Activar'} la habitación ${r.numero}?`))return;try{await api(`/habitaciones/${r.id}`,{method:'PATCH',body:JSON.stringify({numero:r.numero,tipo:r.tipo,capacidad:r.capacidad,precio:r.precio,estado:r.estado,piso:r.piso,activo,observaciones:r.observaciones,hospedajeId:r.hospedajeId})},token);setMsg(`Habitación ${activo==='No'?'desactivada':'activada'}`);load()}catch(x){setMsg(x.message)}};
 return <div className="app"><aside className={open?'side open':'side'}><div className="brand"><span><Building2/></span><div><b>HotelControl</b><small>Gestión de hospedaje</small></div><button className="icon mobile" onClick={()=>setOpen(false)}><X/></button></div><nav>{nav.map(([id,l,I])=><button key={id} className={page===id?'active':''} onClick={()=>{setPage(id);setOpen(false)}}><I/>{l}</button>)}</nav><div className="user"><div className="avatar">{initials(usuario.nombre)}</div><span><b>{usuario.nombre}</b><small>{usuario.rol}</small></span><button className="icon" onClick={logout}><LogOut/></button></div></aside><main><header><button className="icon mobile" onClick={()=>setOpen(true)}><Menu/></button><div><h1>{nav.find(x=>x[0]===page)?.[1]}</h1><p>Gestión centralizada y sencilla</p></div><span className="status"><i/> Sistema activo</span></header>{msg&&<div className="notice" onClick={()=>setMsg('')}>{msg}</div>}<section className="content">{busy?<div className="loading">Cargando información…</div>:<>
 {page==='calendario'&&<CalendarPage month={month} setMonth={setMonth} hospedajes={hospedajes} filter={hotelFilter} setFilter={setHotelFilter} rooms={rooms} bookings={bookings} guest={guest} room={room} onNew={(draft=null)=>{setReservationDraft(draft);setModal(draft?'reservas':'nuevo')}} onSelect={setSelected}/>} 
 {page==='reservas'&&<ReservationsPage bookings={bookings} guest={guest} room={room} hotel={hotel} onNew={()=>{setReservationDraft(null);setModal('nuevo')}} onSelect={setSelected}/>} 
 {page==='registro'&&<RegisterPage rows={registro}/>} 
 {page==='pagos'&&<PaymentsPage dash={dash} bookings={bookings} payments={payments} guest={guest} room={room}/>} 
 {page==='limpieza'&&<CleaningPage rows={cleaning} action={cleaningAction}/>} 
 {page==='mantenimiento'&&<MaintenancePage rows={maintenance} action={maintenanceAction}/>} 
 {page==='config'&&<ConfigPage hospedajes={hospedajes} rooms={rooms} hotel={hotel} addHotel={()=>setModal('hospedajes')} addRoom={()=>setModal('habitaciones')} editHotel={editHotel} toggleHotel={toggleHotel} editRoom={editRoom} toggleRoom={toggleRoom} sendMaintenance={sendMaintenance} sendCleaning={sendCleaning}/>} 
 {page==='usuarios'&&<SimpleTable title="Usuarios" button="Nuevo usuario" onAdd={()=>setModal('usuarios')} headers={['Nombre','Correo','Rol','Estado']} rows={users.map(x=>[x.nombre,x.correo,x.rol,x.estado])}/>}</>}</section></main>
 {modal&&<FormModal type={modal} close={()=>setModal(null)} choose={setModal} save={save} hospedajes={hospedajes} rooms={rooms} bookings={bookings} initial={reservationDraft}/>} {selected&&<DetailModal booking={selected} guest={guest(selected.huespedId)} room={room(selected.habitacionId)} hotel={hotel(room(selected.habitacionId).hospedajeId)} close={()=>setSelected(null)} action={action} payments={payments.filter(p=>p.reservaId===selected.id)} rooms={rooms} deletePayment={deletePayment}/>}</div>
}

function CalendarPage({month,setMonth,hospedajes,filter,setFilter,rooms,bookings,guest,onNew,onSelect}){
 const days=new Date(month.getFullYear(),month.getMonth()+1,0).getDate();
 const list=rooms.filter(r=>r.activo!=='No'&&(filter==='todos'||r.hospedajeId===filter));
 const today=iso(new Date());
 const active=bookings.filter(x=>!['Cancelada','Finalizada'].includes(normalizeBookingState(x.estado)));
 const occupied=active.filter(x=>normalizeBookingState(x.estado)==='Ocupada').length;
 const reserved=active.filter(x=>normalizeBookingState(x.estado)==='Reservada').length;
 const checkins=active.filter(x=>x.entrada===today).length;
 const checkouts=active.filter(x=>x.salida===today).length;
 const cell=(r,d)=>{
   const dateIso=iso(new Date(month.getFullYear(),month.getMonth(),d));
   if(r.estado==='En alquiler')return{status:'en-alquiler',text:'AL',date:dateIso};
   if(r.estado==='Mantenimiento')return{status:'mantenimiento',text:'MT',date:dateIso};
   if(r.estado==='Limpieza')return{status:'limpieza',text:'LP',date:dateIso};
   if(r.estado==='Fuera de servicio')return{status:'fuera-servicio',text:'FS',date:dateIso};
   const relevant=bookings.filter(x=>x.habitacionId===r.id&&normalizeBookingState(x.estado)!=='Cancelada');
   const departing=relevant.find(x=>x.salida===dateIso&&normalizeBookingState(x.estado)!=='Cancelada');
   const arriving=relevant.find(x=>x.entrada===dateIso&&!['Cancelada','Finalizada'].includes(normalizeBookingState(x.estado)));
   if(departing&&arriving&&departing.id!==arriving.id)return{status:'split',date:dateIso,morning:departing,night:arriving};
   const current=relevant.find(x=>dateIso>=x.entrada&&dateIso<x.salida);
   if(current){const state=normalizeBookingState(current.estado);if(state==='Finalizada')return{status:'finalizada',text:initials(guest(current.huespedId).nombre),b:current,date:dateIso};return{status:state==='Ocupada'?'ocupada':'reservada',text:initials(guest(current.huespedId).nombre),b:current,date:dateIso};}
   return{status:'libre',text:'',date:dateIso};
 };
 const renderCell=(c,r)=>{
   if(c.status==='split')return <td className={`split-cell ${c.date===today?'today-cell':''}`} title="Salida en la mañana / ingreso en la noche"><button className={`triangle morning ${normalizeBookingState(c.morning.estado)==='Finalizada'?'finalizada':normalizeBookingState(c.morning.estado).toLowerCase()}`} onClick={()=>onSelect(c.morning)}>{initials(guest(c.morning.huespedId).nombre)}</button><button className={`triangle night ${normalizeBookingState(c.night.estado).toLowerCase()}`} onClick={()=>onSelect(c.night)}>{initials(guest(c.night.huespedId).nombre)}</button></td>;
   return <td className={`${c.status} ${c.date===today?'today-cell':''}`} onClick={()=>c.b?onSelect(c.b):(c.status==='libre'&&onNew({habitacionId:r.id,hospedajeId:r.hospedajeId,entrada:c.date,salida:iso(new Date(parseDate(c.date).getTime()+86400000))}))} title={c.b?'Abrir reserva':c.status==='libre'?'Crear reserva':'Habitación no disponible'}>{c.text}</td>;
 };
 return <><div className="calendar-kpis"><article><b>{occupied}</b><span>Ocupadas</span></article><article><b>{reserved}</b><span>Reservadas</span></article><article><b>{checkins}</b><span>Ingresos hoy</span></article><article><b>{checkouts}</b><span>Salidas hoy</span></article></div>
 <div className="calendar-toolbar"><div className="tabs"><button className={filter==='todos'?'active':''} onClick={()=>setFilter('todos')}>Todos</button>{hospedajes.filter(x=>x.estado!=='Inactivo').map(h=><button key={h.id} className={filter===h.id?'active':''} onClick={()=>setFilter(h.id)}>{h.nombre}</button>)}</div><div className="month-nav"><button onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()-1,1))}><ChevronLeft/></button><strong>{month.toLocaleDateString('es-BO',{month:'long',year:'numeric'})}</strong><button onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()+1,1))}><ChevronRight/></button><button className="today-btn" onClick={()=>setMonth(new Date())}>Hoy</button></div></div>
 <div className="calendar-wrap"><table className="calendar"><thead><tr><th>Habitación</th>{Array.from({length:days},(_,i)=>{const date=new Date(month.getFullYear(),month.getMonth(),i+1);return <th key={i} className={iso(date)===today?'today-column':''}>{i+1}<small>{date.toLocaleDateString('es-BO',{weekday:'short'})}</small></th>})}</tr></thead><tbody>{list.map(r=><tr key={r.id}><th>{r.numero}<small>{r.capacidad} camas · {r.tipo}</small></th>{Array.from({length:days},(_,i)=>renderCell(cell(r,i+1),r))}</tr>)}</tbody></table></div>
 {!list.length&&<div className="empty"><BedDouble/><h2>No hay habitaciones activas</h2><p>Crea o activa habitaciones desde Configuración.</p></div>}
 <div className="legend"><span><i className="libre"/>Libre</span><span><i className="reservada"/>Reservada</span><span><i className="ocupada"/>Ocupada</span><span><i className="finalizada"/>Finalizada</span><span><i className="en-alquiler"/>En alquiler</span><span><i className="mantenimiento"/>Mantenimiento</span></div><button className="primary big" onClick={()=>onNew(null)}><Plus/> Nuevo registro</button></>
}
function ReservationsPage({bookings,guest,room,hotel,onNew,onSelect}){
 const[q,setQ]=useState(''),[filter,setFilter]=useState('Todas');
 const normalized=bookings.map(b=>({...b,estadoVista:normalizeBookingState(b.estado)}));
 const rows=normalized.filter(b=>!['Cancelada','Finalizada'].includes(b.estadoVista)).filter(b=>filter==='Todas'||b.estadoVista===filter).filter(b=>`${guest(b.huespedId).nombre} ${room(b.habitacionId).numero} ${hotel(room(b.habitacionId).hospedajeId).nombre}`.toLowerCase().includes(q.toLowerCase()));
 const occupied=normalized.filter(x=>x.estadoVista==='Ocupada').length,reserved=normalized.filter(x=>x.estadoVista==='Reservada').length;
 return <><div className="stats-mini"><article><b>{occupied}</b><span>Ocupadas</span></article><article><b>{reserved}</b><span>Reservadas</span></article></div><div className="panel"><div className="panelhead"><div className="tabs"><button className={filter==='Todas'?'active':''} onClick={()=>setFilter('Todas')}>Todas</button><button className={filter==='Reservada'?'active':''} onClick={()=>setFilter('Reservada')}>Reservadas</button><button className={filter==='Ocupada'?'active':''} onClick={()=>setFilter('Ocupada')}>Ocupadas</button></div><button className="primary" onClick={onNew}><Plus/> Nuevo</button></div><div className="search"><Search/><input placeholder="Buscar por nombre, habitación u hospedaje" value={q} onChange={e=>setQ(e.target.value)}/></div><div className="booking-list">{rows.length?rows.map(b=>{const g=guest(b.huespedId),r=room(b.habitacionId);return <button key={b.id} className="booking-card" onClick={()=>onSelect(b)}><div className={`initial ${b.estadoVista==='Ocupada'?'red':'yellow'}`}>{initials(g.nombre)}</div><div><b>{g.nombre||'Huésped sin nombre'}</b><span>Hab. {r.numero||'-'} · {hotel(r.hospedajeId).nombre||'Sin hospedaje'}</span><small>{b.entrada} al {b.salida}</small></div><strong className={b.estadoVista==='Ocupada'?'redtxt':'yellowtxt'}>{b.estadoVista}</strong></button>}):<div className="empty"><Search/><h2>Sin resultados</h2><p>No se encontraron reservas con el filtro seleccionado.</p></div>}</div></div></>
}
function RegisterPage({rows}){const[period,setPeriod]=useState('Mes'),[query,setQuery]=useState('');const now=new Date();const filtered=rows.filter(x=>{const d=parseDate(x.salida)||parseDate(x.entrada);if(!d)return true;const sameYear=d.getFullYear()===now.getFullYear();if(period==='Año')return sameYear;if(period==='Mes')return sameYear&&d.getMonth()===now.getMonth();const diff=(now-d)/86400000;return diff>=0&&diff<7}).filter(x=>`${x.nombre} ${x.hospedaje} ${x.habitacion}`.toLowerCase().includes(query.toLowerCase()));const total=filtered.reduce((s,x)=>s+Number(x.total||0),0);const exportCsv=()=>{const csv=['Nombre,Hospedaje,Habitación,Ingreso,Hora ingreso,Salida,Hora salida,Personas,Total pagado,Estado',...filtered.map(x=>`"${x.nombre}","${x.hospedaje}","${x.habitacion}",${x.entrada},${x.horaEntrada||''},${x.salida},${x.horaSalida||''},${x.personas||0},${x.total},${x.estado}`)].join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'}));a.download=`registro-${period.toLowerCase()}.csv`;a.click()};return <div className="panel"><div className="panelhead"><div><h2>Registro de hospedados</h2><p className="muted">Nombre, horas reales, personas y total pagado.</p></div><div className="search compact"><Search/><input placeholder="Buscar huésped, habitación…" value={query} onChange={e=>setQuery(e.target.value)}/></div></div><div className="tabs large">{['Semana','Mes','Año'].map(x=><button key={x} className={period===x?'active':''} onClick={()=>setPeriod(x)}>{x}</button>)}</div><div className="report-cards"><article><small>Total cobrado</small><b>{money(total)}</b></article><article><small>Estadías finalizadas</small><b>{filtered.length}</b></article></div><SimpleTable title="Detalle de hospedados" headers={['Nombre','Hospedaje','Habitación','Ingreso','Hora','Salida','Hora','Personas','Total']} rows={filtered.map(x=>[x.nombre,x.hospedaje,x.habitacion,x.entrada,x.horaEntrada||'-',x.salida,x.horaSalida||'-',x.personas||0,money(x.total)])}/><div className="report-actions"><button onClick={()=>window.print()}><Printer/> Imprimir / PDF</button><button onClick={exportCsv}><Download/> Exportar Excel</button></div></div>}
function PaymentsPage({dash,bookings,payments,guest,room}){const active=bookings.filter(x=>!['Cancelada','Finalizada'].includes(x.estado)&&Number(x.saldo)>0);return <><div className="cards"><article><small>Total cobrado</small><strong>{money(dash.ingresos)}</strong></article><article><small>Saldo pendiente</small><strong>{money(dash.pendiente)}</strong></article><article><small>Pagos registrados</small><strong>{payments.length}</strong></article></div><div className="grid"><article className="panel"><h2>Saldos pendientes</h2>{active.length?active.map(x=><div className="room" key={x.id}><div><b>{guest(x.huespedId).nombre||x.id}</b><span>Hab. {room(x.habitacionId).numero}</span></div><strong className="redtxt">{money(x.saldo)}</strong></div>):<p className="muted">No existen saldos pendientes.</p>}</article><article className="panel"><h2>Últimos pagos</h2>{payments.slice().reverse().slice(0,12).map(x=><div className="room" key={x.id}><div><b>{x.concepto||'Pago'}</b><span>{x.fecha} · {x.metodo}</span></div><strong>{money(x.monto)}</strong></div>)}</article></div></>}
function CleaningPage({rows,action}){const pending=rows.filter(x=>x.estado!=='Finalizada');return <article className="panel"><div className="panelhead"><div><h2>Control de limpieza</h2><p className="muted">Las habitaciones pasan aquí automáticamente después de registrar la salida.</p></div><span className="state-pill on">{pending.length} pendientes</span></div><div className="cleaning-grid">{pending.length?pending.map(x=><section className="cleaning-card" key={x.id}><div className="management-icon"><ClipboardCheck/></div><div className="management-info"><h3>Hab. {x.habitacion}</h3><p>{x.hospedaje}</p><span className={`state-pill ${x.estado==='En proceso'?'working':'off'}`}>{x.estado}</span>{x.responsable&&<small>Responsable: {x.responsable}</small>}</div><div className="cleaning-actions">{x.estado==='Pendiente'?<button className="primary" onClick={()=>action(x.id,'iniciar')}><PlayCircle/> Iniciar</button>:<button className="success" onClick={()=>action(x.id,'finalizar')}><CheckCircle2/> Finalizar</button>}</div></section>):<div className="empty"><CheckCircle2/><h2>Todo limpio</h2><p>No hay habitaciones pendientes de limpieza.</p></div>}</div></article>}
function MaintenancePage({rows,action}){const pending=rows.filter(x=>!['Finalizado','Cancelado'].includes(x.estado));return <article className="panel"><div className="panelhead"><div><h2>Control de mantenimiento</h2><p className="muted">Las habitaciones en mantenimiento no aparecen como disponibles para reservas.</p></div><span className="state-pill maintenance">{pending.length} activos</span></div><div className="cleaning-grid">{pending.length?pending.map(x=><section className="cleaning-card maintenance-card" key={x.id}><div className="management-icon maintenance-icon"><Wrench/></div><div className="management-info"><h3>Hab. {x.habitacion}</h3><p>{x.hospedaje}</p><b>{x.problema}</b><small>Prioridad: {x.prioridad}</small><span className={`state-pill ${x.estado==='En proceso'?'working':'maintenance'}`}>{x.estado}</span>{x.responsable&&<small>Responsable: {x.responsable}</small>}</div><div className="cleaning-actions">{x.estado==='Pendiente'?<button className="primary" onClick={()=>action(x.id,'iniciar')}><PlayCircle/> Iniciar reparación</button>:<button className="success" onClick={()=>action(x.id,'finalizar')}><CheckCircle2/> Finalizar y enviar a limpieza</button>}</div></section>):<div className="empty"><CheckCircle2/><h2>Sin mantenimientos pendientes</h2><p>Todas las habitaciones están operativas.</p></div>}</div></article>}
function ConfigPage({hospedajes,rooms,hotel,addHotel,addRoom,editHotel,toggleHotel,editRoom,toggleRoom,sendMaintenance,sendCleaning}){return <><article className="panel"><div className="panelhead"><div><h2>Hospedajes</h2><p className="muted">Administra uno o varios establecimientos sin perder su historial.</p></div><button className="primary" onClick={addHotel}><Plus/> Nuevo hospedaje</button></div><div className="management-grid">{hospedajes.map(h=><section className={`management-card ${h.estado==='Inactivo'?'disabled':''}`} key={h.id}><div className="management-icon"><Building2/></div><div className="management-info"><h3>{h.nombre}</h3><p>{h.direccion||'Sin dirección registrada'}</p><span className={`state-pill ${h.estado==='Inactivo'?'off':'on'}`}>{h.estado}</span></div><div className="management-actions"><button title="Editar" onClick={()=>editHotel(h)}><Edit3/></button><button title={h.estado==='Inactivo'?'Activar':'Desactivar'} onClick={()=>toggleHotel(h)}><Power/></button></div></section>)}</div></article><article className="panel"><div className="panelhead"><div><h2>Habitaciones</h2><p className="muted">Cada habitación queda asociada al hospedaje seleccionado.</p></div><button className="primary" onClick={addRoom}><Plus/> Nueva habitación</button></div><div className="tablewrap"><table><thead><tr>{['Hospedaje','Habitación','Tipo','Capacidad','Precio','Estado','Activa','Acciones'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rooms.map(r=><tr key={r.id} className={r.activo==='No'?'row-disabled':''}><td>{hotel(r.hospedajeId).nombre}</td><td><b>{r.numero}</b></td><td>{r.tipo}</td><td>{r.capacidad}</td><td>{money(r.precio)}</td><td>{r.estado}</td><td><span className={`state-pill ${r.activo==='No'?'off':'on'}`}>{r.activo==='No'?'No':'Sí'}</span></td><td><div className="table-actions"><button title="Editar" onClick={()=>editRoom(r)}><Edit3/></button><button title="Enviar a limpieza" onClick={()=>sendCleaning(r)} disabled={r.activo==='No'||r.estado==='Ocupada'}><ClipboardCheck/></button><button title="Enviar a mantenimiento" onClick={()=>sendMaintenance(r)} disabled={r.activo==='No'||r.estado==='Ocupada'}><Wrench/></button><button title={r.activo==='No'?'Activar':'Desactivar'} onClick={()=>toggleRoom(r)}><Power/></button></div></td></tr>)}</tbody></table></div></article></>}
function SimpleTable({title,button,onAdd,headers,rows}){return <article className="panel"><div className="panelhead"><h2>{title}</h2>{button&&<button className="primary" onClick={onAdd}><Plus/>{button}</button>}</div><div className="tablewrap"><table><thead><tr>{headers.map(h=><th>{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{r.map((v,j)=><td key={j}>{v}</td>)}</tr>)}</tbody></table></div></article>}
function FormModal({type,close,choose,save,hospedajes,rooms,bookings=[],initial=null}){
 const reservation=type==='reservas'||type==='ingreso';
 const activeHotels=hospedajes.filter(x=>x.estado!=='Inactivo');
 const[hotelId,setHotelId]=useState(initial?.hospedajeId||activeHotels[0]?.id||'');
 const[entrada,setEntrada]=useState(initial?.entrada||iso(new Date()));
 const[salida,setSalida]=useState(initial?.salida||iso(new Date(Date.now()+86400000)));
 const[selectedRoom,setSelectedRoom]=useState(initial?.habitacionId||'');
 const overlaps=(b)=>{
   if(!entrada||!salida||['Cancelada','Finalizada'].includes(b.estado))return false;
   const a=parseDate(entrada),z=parseDate(salida),be=parseDate(b.entrada),bs=parseDate(b.salida);
   return a<bs&&z>be;
 };
 const roomBusy=new Set(bookings.filter(overlaps).map(x=>x.habitacionId));
 const availableRooms=rooms.filter(x=>
   x.activo!=='No'&&x.hospedajeId===hotelId&&!['Mantenimiento','Limpieza','Fuera de servicio'].includes(x.estado)&&
   !roomBusy.has(x.id)&&(!reservation||type!=='ingreso'||x.estado!=='Ocupada')
 );
 if(type==='nuevo')return <div className="overlay"><div className="modal register-choice"><div className="panelhead"><div><small>NUEVO REGISTRO</small><h2>¿Qué deseas hacer?</h2></div><button type="button" className="icon" onClick={close}><X/></button></div><button className="choice-card reserve" onClick={()=>choose('reservas')}><CalendarDays/><span><b>Reservar para después</b><small>Para llamadas o reservas futuras</small></span><ChevronRight/></button><button className="choice-card checkin" onClick={()=>choose('ingreso')}><BedDouble/><span><b>Ingresar ahora</b><small>Para quien llega en este momento</small></span><ChevronRight/></button><div className="choice-help">También puedes tocar una fecha disponible del calendario.</div></div></div>;
 return <div className="overlay"><form className="modal reservation-form" onSubmit={save}><div className="panelhead"><div><small>{type==='ingreso'?'INGRESO DIRECTO':reservation?'RESERVA FUTURA':'NUEVO REGISTRO'}</small><h2>{type==='ingreso'?'Ingresar ahora':reservation?'Reservar para después':`Nuevo ${type}`}</h2></div><button type="button" className="icon" onClick={close}><X/></button></div>
 {type==='hospedajes'&&<><Input n="nombre" l="Nombre del hospedaje"/><Input n="direccion" l="Dirección"/><Select n="estado" l="Estado" opts={['Activo','Inactivo']}/></>}
 {type==='habitaciones'&&<><Select n="hospedajeId" l="Hospedaje" opts={activeHotels.map(x=>[x.id,x.nombre])}/><Input n="numero" l="Nombre o número de habitación"/><Input n="tipo" l="Tipo"/><Input n="capacidad" l="Cantidad de camas / capacidad" type="number"/><Input n="precio" l="Precio por noche" type="number"/><Input n="piso" l="Piso" type="number"/><Select n="estado" l="Estado inicial" opts={['Disponible','En alquiler','Limpieza','Mantenimiento','Fuera de servicio']}/><Input n="observaciones" l="Observaciones"/></>}
 {type==='usuarios'&&<><Input n="nombre" l="Nombre"/><Input n="correo" l="Correo" type="email"/><Input n="password" l="Contraseña temporal" type="password"/><Select n="rol" l="Rol" opts={['Administrador','Recepcionista','Gerencia','Limpieza','Mantenimiento']}/></>}
 {reservation&&<><input type="hidden" name="ingresarAhora" value={type==='ingreso'?'true':''}/><div className="form-section-title">Ubicación y disponibilidad</div><div className="form-two"><label>Hospedaje<select name="hospedajeVista" value={hotelId} onChange={e=>{setHotelId(e.target.value);setSelectedRoom('')}} required><option value="">Seleccione…</option>{activeHotels.map(x=><option key={x.id} value={x.id}>{x.nombre}</option>)}</select></label><label>Habitación<select name="habitacionId" value={selectedRoom} onChange={e=>setSelectedRoom(e.target.value)} required disabled={!availableRooms.length}><option value="">{availableRooms.length?'Seleccione…':'Sin habitaciones disponibles'}</option>{availableRooms.map(x=><option key={x.id} value={x.id}>{x.numero} · {x.tipo} · {money(x.precio)}</option>)}</select></label></div>{!activeHotels.length&&<div className="alert error">No existen hospedajes activos. Créalo primero en Configuración.</div>}{hotelId&&!availableRooms.length&&<div className="availability-warning"><b>No hay habitaciones disponibles para esas fechas.</b><span>Verifica las fechas, activa una habitación o crea una nueva desde Configuración.</span></div>}<div className="form-section-title">Datos del huésped</div><Input n="nombre" l="Nombre completo"/><div className="form-two"><Input n="telefono" l="Teléfono"/><Input n="personas" l="Personas" type="number"/></div><div className="form-section-title">Fechas y cobro</div><div className="form-two"><label>Entrada<input name="entrada" type="date" value={entrada} onChange={e=>setEntrada(e.target.value)} required/></label><label>Salida<input name="salida" type="date" value={salida} min={entrada} onChange={e=>setSalida(e.target.value)} required/></label></div><div className="form-two"><Input n="total" l="Precio acordado total" type="number"/><Input n="pagado" l={type==='ingreso'?'Monto pagado ahora':'Adelanto (opcional)'} type="number" optional/></div><Input n="observaciones" l="Observaciones" optional/></>}
 <button className="primary full" disabled={reservation&&!availableRooms.length}>Guardar</button></form></div>
}
function DetailModal({booking,guest,room,hotel,close,action,payments=[],rooms=[],deletePayment}){
 const[mode,setMode]=useState('');
 const now=new Date(),today=iso(now),currentTime=`${String(now.getHours()).padStart(2,'0')}:${String(now.getMinutes()).padStart(2,'0')}`;
 const state=normalizeBookingState(booking.estado);
 const isReserved=state==='Reservada',isOccupied=state==='Ocupada';
 const total=Number(booking.precio||0),paid=Number(booking.pagado||0),balance=Math.max(0,total-paid);
 const submit=e=>{e.preventDefault();const payload={accion:mode,...Object.fromEntries(new FormData(e.currentTarget))};if(mode==='salida'&&balance>0&&Number(payload.monto||0)<balance){alert(`Debe registrar el saldo pendiente completo: ${money(balance)}`);return;}action(booking.id,payload)};
 const phone=String(guest.telefono||'').replace(/\D/g,'');
 return <div className="overlay"><div className="modal detail"><div className="detail-header"><div><small>RESERVA {booking.id}</small><h2>Detalle de la estadía</h2></div><button className="icon" onClick={close}><X/></button></div>
 <div className="detail-scroll">
 <section><h3>Datos del huésped</h3><b>{guest.nombre||'Huésped'}</b><p>{guest.telefono||'Sin teléfono'}</p><div className="contact"><a href={`tel:${phone}`}><Phone/> Llamar</a><a href={`https://wa.me/${phone.startsWith('591')?phone:`591${phone}`}`} target="_blank" rel="noreferrer">WhatsApp</a></div></section>
 <section className="detail-grid"><span>Hospedaje<b>{hotel.nombre||'Sin asignar'}</b></span><span>Habitación<b>{room.numero||'Sin asignar'} · {room.tipo||''}</b></span><span>Personas<b>{booking.personas||0}</b></span><span>Entrada prevista<b>{booking.entrada||'-'}</b></span><span>Salida prevista<b>{booking.salida||'-'}</b></span><span>Estado<b className={`detail-state ${state.toLowerCase()}`}>{state}</b></span>{booking.fechaIngresoReal&&<span>Ingreso real<b>{booking.fechaIngresoReal} {booking.horaIngreso}</b></span>}{booking.fechaSalidaReal&&<span>Salida real<b>{booking.fechaSalidaReal} {booking.horaSalida||''}</b></span>}</section>
 <section><h3>Cobro</h3><div className="money-summary"><span>Precio acordado<b>{money(total)}</b></span><span>Pagado<b>{money(paid)}</b></span><span>Pendiente<b className={balance>0?'balance-due':'balance-zero'}>{money(balance)}</b></span></div></section>
 {booking.observaciones&&<section><h3>Observaciones</h3><p>{booking.observaciones}</p></section>}
 {payments.length>0&&<section><h3>Historial de pagos</h3><div className="payment-history">{payments.slice().reverse().map(p=><div key={p.id} className={p.estado==='Anulado'?'payment-cancelled':''}><span><b>{p.concepto||'Pago'}</b><small>{p.fecha} · {p.metodo}{p.estado==='Anulado'?' · ANULADO':''}</small></span><strong>{money(p.monto)}</strong>{p.estado!=='Anulado'&&deletePayment&&<button type="button" className="payment-delete" onClick={()=>deletePayment(p.id)} title="Anular pago mal cargado"><X/></button>}</div>)}</div></section>}
 </div>
 {!mode&&<div className="action-stack detail-actions">{isReserved?<><button className="success prominent" onClick={()=>setMode('entrada')}><BedDouble/> Registrar entrada</button><button className="secondary" onClick={()=>setMode('editar')}><Edit3/> Editar reserva</button><button className="danger" onClick={()=>setMode('cancelar')}><X/> Cancelar reserva</button></>:isOccupied?<>{balance>0&&<button className="success" onClick={()=>setMode('pago')}><WalletCards/> Registrar pago</button>}<button className="secondary" onClick={()=>setMode('editar')}><Edit3/> Editar estadía</button><button className="primary" onClick={()=>setMode('salida')}><LogOut/> Registrar salida</button></>:<div className="finished-note">Esta reserva está {state.toLowerCase()} y no admite nuevas operaciones.</div>}</div>}
 {mode&&<form onSubmit={submit} className={`detail-operation ${mode==='entrada'?'checkin-form':''}`}><div className="operation-title"><h3>{mode==='entrada'?'Confirmar ingreso del huésped':mode==='pago'?'Registrar pago':mode==='salida'?'Registrar salida':mode==='cancelar'?'Cancelar reserva':'Editar estadía'}</h3><button type="button" className="icon" onClick={()=>setMode('')}><X/></button></div>
 {mode==='entrada'&&<><div className="checkin-summary"><div><small>Huésped</small><b>{guest.nombre}</b></div><div><small>Hospedaje</small><b>{hotel.nombre}</b></div><div><small>Habitación</small><b>{room.numero}</b></div><div><small>Estado actual</small><b className="reserved-label">Reservada</b></div></div><div className="form-two"><label>Fecha de entrada<input name="fecha" type="date" defaultValue={today} required/></label><label>Hora de entrada<input name="hora" type="time" defaultValue={currentTime} required/></label></div><div className="checkin-info"><CheckCircle2/><span>Al confirmar, la reserva y la habitación cambiarán inmediatamente a <b>Ocupada</b>.</span></div></>}
 {mode==='pago'&&<><Input n="monto" l={`Monto a registrar (pendiente ${money(balance)})`} type="number" defaultValue={balance}/><Select n="metodoPago" l="Forma de pago" opts={['Efectivo','QR','Transferencia']}/><Input n="comprobante" l="N.º de comprobante (opcional)" optional/></>}
 {mode==='salida'&&<><div className="checkout-summary"><span>Precio total<b>{money(total)}</b></span><span>Pagado<b>{money(paid)}</b></span><span>Pendiente<b>{money(balance)}</b></span></div><div className="form-two"><Input n="fecha" l="Fecha de salida" type="date" defaultValue={today}/><Input n="hora" l="Hora de salida" type="time" defaultValue={currentTime}/></div>{balance>0&&<><Input n="monto" l={`Pago final obligatorio (${money(balance)})`} type="number" defaultValue={balance}/><Select n="metodoPago" l="Forma de pago" opts={['Efectivo','QR','Transferencia']}/></>}</>}
 {mode==='editar'&&<><div className="form-two"><Input n="nombreHuesped" l="Nombre completo" defaultValue={guest.nombre}/><Input n="telefono" l="Teléfono" defaultValue={guest.telefono}/></div><div className="form-two"><Input n="entrada" l="Fecha prevista de entrada" type="date" defaultValue={booking.entrada}/><Input n="salida" l="Fecha prevista de salida" type="date" defaultValue={booking.salida}/></div><div className="form-two"><Input n="fechaIngresoReal" l="Ingreso real" type="date" defaultValue={booking.fechaIngresoReal}/><Input n="horaIngreso" l="Hora de ingreso" type="time" defaultValue={booking.horaIngreso}/></div><div className="form-two"><Input n="fechaSalidaReal" l="Salida real" type="date" defaultValue={booking.fechaSalidaReal} optional/><Input n="horaSalida" l="Hora de salida" type="time" defaultValue={booking.horaSalida} optional/></div><label>Habitación<select name="habitacionId" defaultValue={booking.habitacionId}>{rooms.filter(r=>r.activo!=='No'&&!['Mantenimiento','Limpieza','Fuera de servicio','En alquiler'].includes(r.estado)).map(r=><option key={r.id} value={r.id}>{r.numero} · {r.tipo}</option>)}</select></label><div className="form-two"><Input n="total" l="Precio total" type="number" defaultValue={total}/><Input n="personas" l="Personas" type="number" defaultValue={booking.personas}/></div></>}
 {mode==='cancelar'&&<div className="alert error">La reserva quedará cancelada, pero los pagos registrados permanecerán en el historial.</div>}
 <Input n="observaciones" l="Observación" optional={mode==='entrada'}/><div className="action-row sticky-operation"><button type="button" className="secondary" onClick={()=>setMode('')}>Atrás</button><button className={mode==='cancelar'?'danger':mode==='entrada'||mode==='pago'?'success':'primary'}>{mode==='entrada'?'Confirmar entrada':mode==='salida'?'Confirmar salida':mode==='pago'?'Guardar pago':'Confirmar'}</button></div></form>}
 </div></div>
}
function Input({n,l,type='text',optional=false,defaultValue,min,max,step}){return <label>{l}<input name={n} type={type} defaultValue={defaultValue} min={min} max={max} step={step} required={!optional&&n!=='observaciones'}/></label>};function Select({n,l,opts,defaultValue}){return <label>{l}<select name={n} defaultValue={defaultValue||''} required><option value="">Seleccione…</option>{opts.map(o=>Array.isArray(o)?<option key={o[0]} value={o[0]}>{o[1]}</option>:<option key={o}>{o}</option>)}</select></label>}
